image: Visual Studio 2022
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -y

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - ps: $env:PackageOutputPath="$env:APPVEYOR_BUILD_FOLDER\pkg"
  - dotnet restore src\Serilog.Enrichers.MassTransit.sln
  
build:
  verbosity: minimal
  project: src\Serilog.Enrichers.MassTransit.sln

artifacts:
  - path: pkg\*.nupkg
    name: Serilog.Enrichers.MassTransit

deploy:
  - provider: NuGet
    server: https://nuget.pkg.github.com/alethic/index.json
    username: wasabii
    api_key:
      secure: TesO+wcwXOQmyJ8TmdvIohKzwUlBESsSKIkxyT8j2JSrELDxMP4IQ3qs3csi5JFN
    skip_symbols: false
    symbol_server:
    artifact: /.*\.nupkg/

